#define ATOM_SYMBOL                     1
#define ATOM_BOOL                       2
#define ATOM_CHAR                       3
#define ATOM_SINT64                     4
#define ATOM_REAL64                     5
#define ATOM_STRING                     6
#define CELL_FREE                       7
#define CELL_PAIR                       8
#define CELL_VECTOR                     9
#define CELL_CLOSURE                   10
#define CELL_LAMBDA                    11
#define CELL_FFI                       12
#define LPAR                           13
#define RPAR                           14
#define LBR                            15
#define RBR                            16
#define LSQB                           17
#define RSQB                           18
#define SEMICOL                        19
