#define ATOM_SYMBOL                     1
#define ATOM_BOOL                       2
#define ATOM_CHAR                       3
#define ATOM_SINT64                     4
#define ATOM_REAL64                     5
#define ATOM_STRING                     6
#define CELL_FREE                       7
#define CELL_PAIR                       8
#define CELL_VECTOR                     9
#define CELL_INDEX                     10
#define CELL_APPLY                     11
#define CELL_ENVIRONMENT               12
#define CELL_FRAME                     13
#define LPAR                           14
#define RPAR                           15
#define LBR                            16
#define RBR                            17
#define ATOM_UNARY_OP                  18
#define ATOM_BINARY_OP                 19
#define COL                            20
#define LSQB                           21
#define RSQB                           22
