#define ATOM_SYMBOL                     1
#define ATOM_BOOL                       2
#define ATOM_CHAR                       3
#define ATOM_SINT64                     4
#define ATOM_REAL64                     5
#define ATOM_STRING                     6
#define ATOM_ERROR                      7
#define CELL_LIST                       8
#define CELL_VECTOR                     9
#define CELL_LAMBDA                    10
#define CELL_QUOTE                     11
#define CELL_CLOSURE                   12
#define CELL_FFI                       13
#define CELL_BIND                      14
#define LPAR                           15
#define RPAR                           16
#define LBR                            17
#define RBR                            18
#define LSQB                           19
#define RSQB                           20
#define SEMICOL                        21
