#define TOK_SYMBOL                      1
#define TOK_BOOL                        2
#define TOK_CHAR                        3
#define TOK_SINT64                      4
#define TOK_REAL64                      5
#define TOK_STRING                      6
#define TOK_LPAR                        7
#define TOK_RPAR                        8
#define TOK_LBR                         9
#define TOK_RBR                        10
#define TOK_LSQB                       11
#define TOK_RSQB                       12
#define TOK_SEMICOL                    13
#define TOK_OP_UNARY                   14
#define TOK_OP_BIN0                    15
#define TOK_OP_BIN1                    16
#define TOK_OP_BIN2                    17
#define TOK_OP_BIN3                    18
